import type { CreditCard } from "@/types";

/**
 * SAMPLE / ILLUSTRATIVE DATA — NOT REAL PRODUCT TERMS.
 *
 * Issuer names are real Saudi banks, but card names, fees, rates, rewards and
 * eligibility thresholds below are placeholders for the MVP. Replace with
 * verified, partner-provided data before any public launch.
 */
export const CARDS: CreditCard[] = [
  {
    id: "rajhi-cashback-platinum",
    issuer: { ar: "مصرف الراجحي", en: "Al Rajhi Bank" },
    name: { ar: "كاش باك بلاتينيوم", en: "Cashback Platinum" },
    network: "visa",
    type: "cashback",
    shariaCompliant: true,
    annualFeeSAR: 0,
    annualFeeWaiverSpendSAR: 0,
    minMonthlyIncomeSAR: 5000,
    minAge: 18,
    aprPercent: 0,
    rewards: {
      type: "cashback",
      base: 0.01,
      categories: { groceries: 0.05, dining: 0.03, fuel: 0.04 },
      annualCapSAR: 3000,
    },
    benefits: [
      { ar: "بدون رسوم سنوية", en: "No annual fee" },
      { ar: "متوافق مع الشريعة", en: "Shariah-compliant" },
      { ar: "كاش باك 5% على البقالة", en: "5% cashback on groceries" },
    ],
    accent: "#1E7A46",
  },
  {
    id: "rajhi-travel-signature",
    issuer: { ar: "مصرف الراجحي", en: "Al Rajhi Bank" },
    name: { ar: "ترافل سيجنتشر", en: "Travel Signature" },
    network: "visa",
    type: "travel",
    shariaCompliant: true,
    annualFeeSAR: 600,
    annualFeeWaiverSpendSAR: 60000,
    minMonthlyIncomeSAR: 12000,
    minAge: 21,
    aprPercent: 0,
    rewards: {
      type: "points",
      base: 1,
      categories: { travel: 3, international: 3, dining: 2 },
      pointValue: 0.04,
      annualCapSAR: 5000,
    },
    benefits: [
      { ar: "دخول صالات المطارات", en: "Airport lounge access" },
      { ar: "متوافق مع الشريعة", en: "Shariah-compliant" },
      { ar: "3 نقاط لكل ريال على السفر", en: "3 points per SAR on travel" },
    ],
    accent: "#1F3A5F",
  },
  {
    id: "snb-rewards-world-elite",
    issuer: { ar: "البنك الأهلي السعودي", en: "Saudi National Bank" },
    name: { ar: "ريواردز وورلد إيليت", en: "Rewards World Elite" },
    network: "mastercard",
    type: "rewards",
    shariaCompliant: false,
    annualFeeSAR: 750,
    annualFeeWaiverSpendSAR: 75000,
    minMonthlyIncomeSAR: 15000,
    minAge: 21,
    aprPercent: 34.0,
    rewards: {
      type: "points",
      base: 1.5,
      categories: { dining: 3, online: 2, travel: 2 },
      pointValue: 0.03,
      annualCapSAR: 6000,
    },
    benefits: [
      { ar: "نقاط مضاعفة على المطاعم", en: "Bonus points on dining" },
      { ar: "تأمين سفر", en: "Travel insurance" },
      { ar: "خدمة كونسيرج", en: "Concierge service" },
    ],
    accent: "#2E75B6",
  },
  {
    id: "snb-everyday-cashback",
    issuer: { ar: "البنك الأهلي السعودي", en: "Saudi National Bank" },
    name: { ar: "كاش باك اليومي", en: "Everyday Cashback" },
    network: "mada",
    type: "cashback",
    shariaCompliant: false,
    annualFeeSAR: 0,
    minMonthlyIncomeSAR: 4000,
    minAge: 18,
    aprPercent: 32.0,
    rewards: {
      type: "cashback",
      base: 0.015,
      categories: { groceries: 0.03, fuel: 0.03 },
      annualCapSAR: 2000,
    },
    benefits: [
      { ar: "بدون رسوم سنوية", en: "No annual fee" },
      { ar: "كاش باك على الوقود والبقالة", en: "Cashback on fuel & groceries" },
    ],
    accent: "#1B5A94",
  },
  {
    id: "riyad-fuel-groceries",
    issuer: { ar: "بنك الرياض", en: "Riyad Bank" },
    name: { ar: "كاش باك الوقود والبقالة", en: "Fuel & Groceries Cashback" },
    network: "visa",
    type: "cashback",
    shariaCompliant: false,
    annualFeeSAR: 300,
    annualFeeWaiverSpendSAR: 30000,
    minMonthlyIncomeSAR: 6000,
    minAge: 18,
    aprPercent: 33.5,
    rewards: {
      type: "cashback",
      base: 0.01,
      categories: { fuel: 0.06, groceries: 0.04 },
      annualCapSAR: 2400,
    },
    benefits: [
      { ar: "كاش باك 6% على الوقود", en: "6% cashback on fuel" },
      { ar: "تُلغى الرسوم مع الإنفاق", en: "Fee waived with spend" },
    ],
    accent: "#0E4C7A",
  },
  {
    id: "albilad-sharia-rewards",
    issuer: { ar: "بنك البلاد", en: "Bank Albilad" },
    name: { ar: "مكافآت بلاتينيوم", en: "Rewards Platinum" },
    network: "visa",
    type: "rewards",
    shariaCompliant: true,
    annualFeeSAR: 0,
    minMonthlyIncomeSAR: 5000,
    minAge: 18,
    aprPercent: 0,
    rewards: {
      type: "points",
      base: 1.25,
      categories: { online: 2, dining: 2 },
      pointValue: 0.035,
      annualCapSAR: 3500,
    },
    benefits: [
      { ar: "متوافق مع الشريعة", en: "Shariah-compliant" },
      { ar: "بدون رسوم سنوية", en: "No annual fee" },
      { ar: "نقاط على التسوق الإلكتروني", en: "Points on online shopping" },
    ],
    accent: "#1E7A46",
  },
  {
    id: "alinma-travel-infinite",
    issuer: { ar: "مصرف الإنماء", en: "Alinma Bank" },
    name: { ar: "ترافل إنفينيت", en: "Travel Infinite" },
    network: "visa",
    type: "travel",
    shariaCompliant: true,
    annualFeeSAR: 900,
    annualFeeWaiverSpendSAR: 120000,
    minMonthlyIncomeSAR: 20000,
    minAge: 25,
    aprPercent: 0,
    rewards: {
      type: "points",
      base: 1.5,
      categories: { travel: 4, international: 3, dining: 2 },
      pointValue: 0.045,
      annualCapSAR: 8000,
    },
    benefits: [
      { ar: "دخول غير محدود للصالات", en: "Unlimited lounge access" },
      { ar: "متوافق مع الشريعة", en: "Shariah-compliant" },
      { ar: "4 نقاط لكل ريال على السفر", en: "4 points per SAR on travel" },
    ],
    accent: "#0B3D2E",
  },
  {
    id: "alinma-basic",
    issuer: { ar: "مصرف الإنماء", en: "Alinma Bank" },
    name: { ar: "البطاقة الأساسية", en: "Essential Card" },
    network: "mada",
    type: "basic",
    shariaCompliant: true,
    annualFeeSAR: 0,
    minMonthlyIncomeSAR: 3000,
    minAge: 18,
    aprPercent: 0,
    rewards: {
      type: "cashback",
      base: 0.005,
      categories: {},
      annualCapSAR: 1000,
    },
    benefits: [
      { ar: "متوافق مع الشريعة", en: "Shariah-compliant" },
      { ar: "حد أدنى منخفض للدخل", en: "Low income requirement" },
    ],
    accent: "#2E7D5B",
  },
  {
    id: "sab-world-travel",
    issuer: { ar: "البنك السعودي الأول", en: "Saudi Awwal Bank" },
    name: { ar: "وورلد ترافل", en: "World Travel" },
    network: "mastercard",
    type: "travel",
    shariaCompliant: false,
    annualFeeSAR: 700,
    annualFeeWaiverSpendSAR: 70000,
    minMonthlyIncomeSAR: 15000,
    minAge: 21,
    aprPercent: 34.5,
    rewards: {
      type: "points",
      base: 1,
      categories: { travel: 3, international: 3, online: 2 },
      pointValue: 0.04,
      annualCapSAR: 5500,
    },
    benefits: [
      { ar: "أميال على شركاء الطيران", en: "Airline partner miles" },
      { ar: "تأمين سفر عالمي", en: "Global travel insurance" },
    ],
    accent: "#7A1F2B",
  },
  {
    id: "anb-cashback-titanium",
    issuer: { ar: "البنك العربي الوطني", en: "Arab National Bank" },
    name: { ar: "كاش باك تيتانيوم", en: "Cashback Titanium" },
    network: "visa",
    type: "cashback",
    shariaCompliant: false,
    annualFeeSAR: 250,
    annualFeeWaiverSpendSAR: 25000,
    minMonthlyIncomeSAR: 5000,
    minAge: 18,
    aprPercent: 33.0,
    rewards: {
      type: "cashback",
      base: 0.02,
      categories: { dining: 0.04, online: 0.03 },
      annualCapSAR: 2500,
    },
    benefits: [
      { ar: "كاش باك 2% على كل الإنفاق", en: "2% cashback on everything" },
      { ar: "كاش باك 4% على المطاعم", en: "4% cashback on dining" },
    ],
    accent: "#12507A",
  },
  {
    id: "bsf-rewards-platinum",
    issuer: { ar: "البنك السعودي الفرنسي", en: "Banque Saudi Fransi" },
    name: { ar: "مكافآت بلاتينيوم", en: "Rewards Platinum" },
    network: "mastercard",
    type: "rewards",
    shariaCompliant: false,
    annualFeeSAR: 400,
    annualFeeWaiverSpendSAR: 40000,
    minMonthlyIncomeSAR: 8000,
    minAge: 18,
    aprPercent: 33.0,
    rewards: {
      type: "points",
      base: 1.25,
      categories: { dining: 2, groceries: 2, online: 2 },
      pointValue: 0.03,
      annualCapSAR: 4000,
    },
    benefits: [
      { ar: "نقاط على المطاعم والبقالة", en: "Points on dining & groceries" },
      { ar: "برنامج استبدال مرن", en: "Flexible redemption program" },
    ],
    accent: "#1F3A5F",
  },
];

export function getCardById(id: string): CreditCard | undefined {
  return CARDS.find((c) => c.id === id);
}
